### ISSUE TITLE
Loading data form keyerror

### ISSUE THREAD

**Issue by LookLikeAPro** [semente/django-smuggler#54]
This is using python 3.5 and Django 1.9
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 213, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/local/lib/python3.5/site-packages/smuggler/views.py", line 87, in get_context_data
    adminform=self.get_admin_form(kwargs['form']),
KeyError: 'form'
```

**Comment by LookLikeAPro** [comment]
This error doesn't happen when I copy code from this repo instead of using pip. Is the pip version not up to date?

**Comment by semente** [comment]
The PyPI release is 0.6.1, which does not have Django 1.9 support. You must use Git version for now. I will release a new version next days, thanks!

**Comment by jaap3** [comment]
If one of you could look at #52 (and possible fix whatever is wrong) before releasin, that would be great. I don't have the time (and I haven't used smuggler for a while now).

**Comment by fzdmd** [comment]
Same problem

**Comment by semente** [comment]
PyPI now contains new release 0.7.0. You are cool now.
